# Generated by Django 5.1.4 on 2026-06-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectitemline_source_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='operation_access_status',
            field=models.CharField(
                choices=[
                    ('none', 'Locked (awaiting paid invoice or approval)'),
                    ('pending', 'Operation access request pending'),
                    ('approved', 'Operation access approved'),
                    ('rejected', 'Operation access rejected'),
                ],
                default='none',
                help_text='Estimate-sourced projects stay locked until a paid invoice or approver grants access.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='operation_access_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operation_access_submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='project_operation_access_submissions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
