# Generated by Django 4.2.11 on 2026-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_approval_rejection_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_attachment',
            field=models.FileField(blank=True, help_text='Optional file supporting the project status (e.g. completion certificate or approval document).', max_length=500, upload_to='project_status/%Y/%m/', verbose_name='Status attachment'),
        ),
    ]
