# Generated by Django 4.2.11 on 2026-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_status_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edit_approval_submission_note',
            field=models.TextField(blank=True, help_text='Optional note from the submitter when requesting completion.'),
        ),
    ]
