# Generated by Django 4.2.11 on 2026-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_completion_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lpo_number',
            field=models.CharField(blank=True, help_text='Customer local purchase order / PO reference for this project.', max_length=100, verbose_name='LPO number'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', help_text='Agreed payment terms for this project (e.g. Net 30).', max_length=50),
        ),
    ]
