# Generated by Django 5.1.4 on 2026-10-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventory_approval_workflows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-item_code']},
        ),
    ]
