# Generated by Django 5.1.4 on 2026-07-07 13:10

import apps.finance.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_account_mapping_advance_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payments/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx', 'docx']), apps.finance.models.validate_payment_attachment_size]),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cash_account': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='finance.account'),
        ),
    ]
