# Generated by Django 5.1.4 on 2026-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_tax_credit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_prices_include_vat',
            field=models.BooleanField(default=False, help_text='Default for new sales estimates and invoices: prices include VAT'),
        ),
    ]
