# Generated by Django 5.1.4 on 2026-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_vat_inclusive_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('sales', 'Sales Invoice'), ('purchase', 'Vendor Bill'), ('payment', 'Payment'), ('bank_transfer', 'Bank Transfer'), ('expense_claim', 'Expense Claim'), ('payroll', 'Payroll'), ('inventory', 'Inventory Movement'), ('fixed_asset', 'Fixed Asset'), ('project', 'Project Expense'), ('pdc', 'PDC Cheque'), ('property', 'Property/Rent'), ('vat', 'VAT Adjustment'), ('corporate_tax', 'Corporate Tax'), ('opening_balance', 'Opening Balance'), ('year_end', 'Year-End Closing'), ('reversal', 'Reversal Entry'), ('adjustment', 'Manual Adjustment'), ('sales_credit_note', 'Sales Credit Note'), ('purchase_debit_note', 'Purchase Debit Note'), ('finance_payment', 'Finance Payment')], default='manual', help_text='Module that created this journal entry', max_length=50),
        ),
    ]
