# Generated by Django 5.1.4 on 2026-07-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_journalentry_source_module_credit_debit_note'),
        ('purchase', '0025_debit_notes'),
        ('sales', '0031_vat_inclusive_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='purchase.vendorbill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='sales.invoice'),
        ),
    ]
