# Generated by Django 5.1.4 on 2026-09-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_pdc_customer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdccheque',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('deposited', 'Deposited'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('returned', 'Returned to Customer'), ('replaced', 'Replaced'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
