# Generated by Django 5.1.4 on 2026-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_tax_credit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='prices_include_vat',
            field=models.BooleanField(default=False, help_text='If true, entered line rates are VAT-inclusive; VAT is back-calculated.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prices_include_vat',
            field=models.BooleanField(default=False, help_text='If true, entered unit prices are VAT-inclusive; VAT is back-calculated.'),
        ),
    ]
