# Generated by Django 5.1.4 on 2026-10-05 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0003_stocktakeline_scan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktakesession',
            name='public_scan_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret token for the public camera page (no login).', unique=True),
        ),
    ]
