# Generated by Django 5.0 on 2026-06-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectitemline_source_estimate'),
        ('purchase', '0021_purchaserequest_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(
                blank=True,
                help_text='If set, costs from bills linked to this PO can be charged to this project.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchase_orders',
                to='projects.project',
            ),
        ),
    ]
