# Generated by Django 5.1.4 on 2026-07-07 19:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_debit_notes'),
        ('purchase', '0024_remove_purchaserequest_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('vendor_credit_note_ref', models.CharField(max_length=100)),
                ('vendor_credit_note_date', models.DateField()),
                ('reason', models.CharField(choices=[('goods_returned', 'Goods Returned'), ('overbilled', 'Overbilled'), ('pricing_error', 'Pricing Error'), ('vat_error', 'VAT Error'), ('supply_cancelled', 'Supply Cancelled'), ('other', 'Other')], default='goods_returned', max_length=30)),
                ('reason_description', models.TextField(blank=True)),
                ('vendor_trn', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_bill_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bill balance remaining after this debit note is posted.', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='finance.journalentry')),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='purchase.vendorbill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('bill_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_lines', to='purchase.vendorbillitem')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.debitnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
