# Generated by Django 4.2.11 on 2026-09-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_status_attachment'),
        ('purchase', '0028_vendor_website_and_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional project this claim relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='projects.project'),
        ),
    ]
