# Generated by Django 4.2.11 on 2026-09-23 07:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_vendorbill_discount_roundoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='prices_include_vat',
            field=models.BooleanField(default=False, help_text='If true, unit prices on line items include VAT'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment applied to grand total (e.g. fils rounding)', max_digits=15),
        ),
    ]
