# Generated by Django 5.1.4 on 2026-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0025_project_operation_access_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('inventory_item', 'Inventory Item Creation'), ('inventory_adjustment', 'Inventory Stock Adjustment'), ('service_request', 'Service Request'), ('estimate', 'Sales Estimate'), ('project', 'Project'), ('project_conversion', 'Project from estimate (draft)'), ('project_operation_access', 'Project operation access (estimate)'), ('leave', 'Leave Request')], max_length=50, unique=True),
        ),
    ]
