# Generated by Django 5.1.4 on 2026-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created_by_alter_document_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='alert_days_before',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Days before expiry to flag renewal. Leave blank to disable expiry alerts for this type.', null=True),
        ),
    ]
