# Generated by Django 4.2.11 on 2026-10-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_item_options'),
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_items', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='servicerequestitem',
            name='service_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
