# Generated by Django 5.1.4 on 2026-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_uae_eosg_gratuity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('biometric', 'Biometric'), ('public_link', 'Public link'), ('self_service', 'Self-service'), ('bulk_present', 'Mark all present')], default='manual', max_length=20),
        ),
    ]
