# Generated by Django 5.1.4 on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_customer_name_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crmleadkanbanstage',
            name='tracks_opportunity',
            field=models.BooleanField(
                default=False,
                help_text='Leads in this stage track opportunity status (Open / Pending / Close) and updates.',
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='trade_license_number',
            field=models.CharField(
                blank=True,
                help_text='Trade license number for B2B customers.',
                max_length=120,
                verbose_name='Trade license number',
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='opportunity_status',
            field=models.CharField(
                blank=True,
                choices=[('', '—'), ('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')],
                default='',
                help_text='Lead opportunity lifecycle when in a pipeline stage that tracks opportunities.',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='CrmOpportunityUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_updates', to='crm.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM opportunity update',
                'verbose_name_plural': 'CRM opportunity updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
