# Generated by Django 5.1.4 on 2026-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_crm_site_visit_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-customer_number'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='trade_license_document',
            field=models.FileField(blank=True, help_text='Optional. Trade license (PDF or image) for B2B.', max_length=500, upload_to='crm/customer_documents/%Y/%m/', verbose_name='Trade license'),
        ),
    ]
