# Generated by Django 4.2.11 on 2026-09-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_completion_note'),
        ('contracts', '0006_contract_draft_terminated_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional linked project for this contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project'),
        ),
    ]
